#!/bin/bash

config_path=~/.yaes.conf

action=""
current_dir=${HOME}
# follow log filename pattern: ${target}.${protocol}.${port}.${tool}
logs_path="${HOME}/.yaes/logs"

arg_number=${#}
mode=${1}
option_2=${2}
option_3=${3}

status_file="${logs_path}/${target}/.status"
raw_logfile="${logs_path}/${target}/raw_log"
service_file="${logs_path}/${target}/services"
ports_file="${logs_path}/${target}/ports"

red='\033[0;31m'
green='\033[0;32m'
no_color='\033[0m'

# services
web_services=0
samba_services=0
msrpc_services=0
ftp_services=0
ssh_services=0
dns_services=0
mysql_services=0
smtp_services=0
snmp_services=0
oracle_services=0
wordpress_found=0

# multiple ports
http_enum=0
samba_enum=0

http_enumeration_lock="${logs_path}/${target}/http.lock"

nmap_logs="${logs_path}/${target}/nmap"
amap_logs="${logs_path}/${target}/amap"
wpscan_logs="${logs_path}/${target}/wpscan"
samba_logs="${logs_path}/${target}/samba"
nikto_logs="${logs_path}/${target}/nikto"
gobuster_logs="${logs_path}/${target}/gobuster"
gobuster_logfile="${logs_path}/${target}/gobuster"
whatweb_logs="${logs_path}/${target}/whatweb"
whatweb_logfile="${logs_path}/${target}/whatweb/${target}.whatweb.logfile"
fimap_logs="${logs_path}/${target}/fimap"
fimap_logfile="${logs_path}/${target}/fimap/${target}.fimap.log"
webdav_logs="${logs_path}/${target}/webdav"
hydra_logs="${logs_path}/${target}/hydra"
yasuo_logs="${logs_path}/${target}/yasuo"
yasuo_logfile="${logs_path}/${target}/yasuo/${target}.yasuo"

initial_scan_logfile="${nmap_logs}/${target}.tcp.init.log"
tcp_quick_logfile="${nmap_logs}/${target}.tcp.nmap.quick.log"
udp_quick_logfile="${nmap_logs}/${target}.udp.nmap.quick.log"
vulnerabilities_logfile="${logs_path}/${target}/vulnerabilities.scan.log"
samba_logfile="${logs_path}/${target}/samba.log"
msrpc_logfile="${logs_path}/${target}/msrpc.log"
ftp_logfile="${logs_path}/${target}/ftp.log"
ssh_logfile="${logs_path}/${target}/ssh.log"
smtp_logfile="${logs_path}/${target}/smtp.log"
snmp_logfile="${logs_path}/${target}/snmp.log"
http_logfile="${logs_path}/${target}/http.log"
mysql_logfile="${logs_path}/${target}/mysql.log"
oracle_logfile="${logs_path}/${target}/oracle.log"
tomcat_bruteforce_logfile="${logs_path}/${target}/tomcat-brute.log"

# windows database for exploits
database=${repository_root}/privilege-escalation/windows-exploit-suggester/2018-02-11-mssb.xls

tcp_deep_scan=0
udp_deep_scan=0

no_udp=0
no_tcp=0

skip_tcp=0
skip_short_udp=0
skip_udp=1

long_jobs_pids=( )
tcp_deep_scan=0
udp_deep_scan=0

# skip all long scans, instead use files present on disk
developer_mode=0
